name: Build

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build ğŸ—ï¸
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper ğŸ“
        uses: gradle/wrapper-validation-action@v1

      - name: Copy CI gradle.properties ğŸ“‹
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties        

      - name: Set up JDK 17 âš™ï¸
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle âš™ï¸
        uses: gradle/gradle-build-action@v2

      - name: Build all build type and flavor permutations ğŸ—ï¸
        run: ./gradlew assembleDemoDebug
  
      - name: ğŸ“Š Upload build outputs (APKs)
        uses: actions/upload-artifact@v3
        with:
          name: APKs
          path: '**/build/outputs/apk/**/*.apk'

  spotless-check:
    name: Spotless Check ğŸ“
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper ğŸ“
        uses: gradle/wrapper-validation-action@v1

      - name: Copy CI gradle.properties ğŸ“‹
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties        

      - name: Set up JDK 17 âš™ï¸
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle âš™ï¸
        uses: gradle/gradle-build-action@v2

      - name: Check spotless ğŸ“
        run: ./gradlew spotlessCheck --init-script gradle/init.gradle.kts --no-configuration-cache

  lint:
    name: Lint Check ğŸ’…
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper ğŸ“
        uses: gradle/wrapper-validation-action@v1

      - name: Copy CI gradle.properties ğŸ“‹
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties        

      - name: Set up JDK 17 âš™ï¸
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle âš™ï¸
        uses: gradle/gradle-build-action@v2

      - name: Check lint ğŸ’…
        run: ./gradlew lintDemoDebug
        
      - name: ğŸ“Š Upload lint reports (HTML)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: lint-reports
          path: '**/build/reports/lint-results-*.html'

  unit-test:
    name: Build ğŸ—ï¸
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper ğŸ“
        uses: gradle/wrapper-validation-action@v1

      - name: Copy CI gradle.properties ğŸ“‹
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties        

      - name: Set up JDK 17 âš™ï¸
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle âš™ï¸
        uses: gradle/gradle-build-action@v2

      - name: Run local tests ğŸ§ª
        run: ./gradlew testDemoDebug testProdDebug

      - name: ğŸ“Š Upload test results (XML)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: '**/build/test-results/test*UnitTest/**.xml'

  androidTest:
    if: false # disabled bc packageDemoDebugAndroidTest is failing
    name: Android Test ğŸ§ª
    needs: build
    runs-on: macos-latest # enables hardware acceleration in the virtual machine
    timeout-minutes: 90
    strategy:
      matrix:
        api-level: [26, 30]

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
      
      - name: Copy CI gradle.properties ğŸ“‹
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 17 âš™ï¸
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle âš™ï¸
        uses: gradle/gradle-build-action@v2

      - name: Build AndroidTest apps ğŸ—ï¸
        run: ./gradlew packageDemoDebug packageDemoDebugAndroidTest --daemon

      - name: Run instrumentation tests ğŸ§ª
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          disable-animations: true
          disk-size: 6000M
          heap-size: 600M
          script: ./gradlew connectedDemoDebugAndroidTest --daemon

      - name: ğŸ“Š Upload test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports-${{ matrix.api-level }}
          path: '**/build/reports/androidTests'

  androidTest-GMD:
    if: false # disabled bc packageDemoDebugAndroidTest is failing
    name: Android Test GMD ğŸ§ª
    needs: build
    runs-on: macos-latest # enables hardware acceleration in the virtual machine
    timeout-minutes: 90

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Copy CI gradle.properties ğŸ“‹
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 17 âš™ï¸
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle âš™ï¸
        uses: gradle/gradle-build-action@v2

      - name: Accept Android licenses âœ”ï¸
        run: yes | "$ANDROID_HOME"/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - name: Build AndroidTest apps ğŸ—ï¸
        run: ./gradlew packageDemoDebug packageDemoDebugAndroidTest

      - name: Run instrumented tests with GMD ğŸ§ª
        run: ./gradlew cleanManagedDevices --unused-only &&
          ./gradlew ciDemoDebugAndroidTest -Dorg.gradle.workers.max=1
          -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect" -Pandroid.experimental.testOptions.managedDevices.emulator.showKernelLogging=true

      - name: ğŸ“Š Upload test reports
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: '**/build/reports/androidTests'
